# Generated by Django 3.1.5 on 2021-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherpool",
            name="success_message",
            field=models.TextField(
                blank=True,
                help_text="Message to display to participants when claiming a voucher. Useful for instructions on how to use the vouchers.",
            ),
        ),
        migrations.AlterField(
            model_name="voucherpool",
            name="empty_pool_message",
            field=models.TextField(
                blank=True,
                help_text="Message to display to participants when the voucher pool has run out of vouchers.",
            ),
        ),
    ]
