# Generated by Django 3.1.5 on 2021-02-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursement", "0002_voucher_success_message"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voucher",
            unique_together={("code", "pool")},
        ),
    ]
