# Generated by Django 3.1.5 on 2021-01-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_policy',
            field=models.TextField(blank=True),
        ),
    ]
