# Generated by Django 3.1.6 on 2021-03-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_config", "0002_siteconfiguration_privacy_policy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="privacy_policy",
            new_name="participant_privacy_policy",
        ),
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="terms_and_conditions",
            new_name="participant_terms_and_conditions",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="researcher_privacy_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="researcher_terms_and_conditions",
            field=models.TextField(blank=True),
        ),
    ]
