# Generated by Django 3.2.1 on 2021-08-11 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_expand_site_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='researcher_terms_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
