# Generated by Django 3.1.2 on 2020-11-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
