# Generated by Django 3.1.6 on 2021-03-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_job_title_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_terms_at',
            field=models.DateTimeField(null=True),
        ),
    ]
